name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  token:
    description: 'A GitHub token.'
    required: true
  repository:
    description: 'The full name of the repository to create or update a comment. Defaults to the current repository.'
  issue-number:
    description: 'The issue number to create a comment.'
  comment-id:
    description: 'The comment id to update a comment.'
  body:
    description: 'The comment body.'
  edit-mode:
    description: 'When updating a comment, "replace" or "append".'
  reaction-type:
    description: 'The reaction to add to the comment.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
