name: Hello World Pull Request Command
on:
  repository_dispatch:
    types: [hello-world-pr-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      # For debugging purposes. Remove this in production.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # For debugging purposes. Remove this in production.
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      # - name: Create comment
      #   #uses: peter-evans/create-or-update-comment@v1
      #   uses: ./.github/create-or-update-comment
      #   with:
      #     token: ${{ secrets.ACTIONS_BOT_TOKEN }}
      #     repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
      #     issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
      #     body: |
      #       Hello @${{ github.event.client_payload.github.actor }}!

      - name: Add reaction
        #uses: peter-evans/create-or-update-comment@v1
        uses: ./.github/create-or-update-comment
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
